# Generated by Django 4.1.7 on 2023-03-18 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_scan_name_alter_scan_har_file_alter_scan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scans.scan')),
                ('raw_results', models.JSONField()),
            ],
        ),
    ]
