# Generated by Django 4.1.7 on 2023-03-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_remove_scan_har_file_scanresult_audio_load_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='content_load_time',
        ),
    ]
